FROM jenkins/jenkins:lts-alpine
LABEL maintainer="Tobias Derksen <tobias.derksen@student.fontys.nl>"

USER root

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

RUN apk --no-cache add curl git docker shadow sudo maven
RUN apk --no-cache --upgrade add php7 php7-common libedit libxml2 musl pcre php7-fpm php7-mysqli php7-json php7-openssl php7-curl php7-redis \
    php7-zlib php7-xml php7-phar php7-pdo php7-pdo_mysql php7-pdo_sqlite php7-intl php7-dom php7-xmlreader php7-ctype \
    php7-mbstring php7-gd php7-sqlite3 php7-session php7-tokenizer php7-simplexml php7-xmlwriter \
    nodejs nodejs-npm yarn ncurses ncurses-libs zlib

RUN curl -L https://github.com/docker/compose/releases/download/1.17.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
RUN gpasswd -a jenkins docker
RUN sed -i.bak '2i sudo chgrp docker /var/run/docker.sock' /usr/local/bin/jenkins.sh

USER jenkins
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt

VOLUME /var/jenkins_home
